import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-row justify-between p-6 m-6 items-center ring-2 ring-black/15 rounded-3xl inset-shadow-sm inset-shadow-black/50 ">
          <div className="flex flex-row gap-4 items-center">
            <h1 className="text-4xl text-shadow-md px-4">Killswitch</h1>
          </div>
          <div className="flex flex-row gap-4 items-center">
            <button className="font-semibold bg-black text-white px-6 py-4 rounded-2xl hover:bg-black/50">Pricing</button>
            <button className="font-semibold bg-black text-white px-6 py-4 rounded-2xl hover:bg-black/50">Request Demo</button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
